# Generated by Django 2.0.4 on 2018-05-03 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.DecimalField(decimal_places=2, max_digits=4)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hair_color', models.CharField(choices=[('bl', 'BLACK'), ('rh', 'REDHEAD'), ('ga', 'GRAY'), ('gr', 'GREEN'), ('bd', 'BALD')], max_length=255)),
                ('eye_color', models.CharField(choices=[('gr', 'GREEN'), ('bl', 'BLUE'), ('ch', 'CHESNUT'), ('ga', 'GRAY'), ('bl', 'BLACK'), ('br', 'BROWN')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Suitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('gender', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=128)),
                ('dob', models.DateField()),
                ('age', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='characteristics',
            name='suitor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suitor.Suitor'),
        ),
    ]
