# Generated by Django 2.0.4 on 2018-05-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suitor', '0003_remove_suitor_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='suitor',
            name='registration_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
