# Generated by Django 2.0.4 on 2018-05-04 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suitor', '0004_suitor_registration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aprnc',
            old_name='suiter_id',
            new_name='suitor_id',
        ),
    ]
