# Generated by Django 2.0.4 on 2018-05-05 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suitor', '0006_auto_20180504_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aprnc',
            old_name='width',
            new_name='height',
        ),
    ]
