# Generated by Django 2.0.4 on 2018-05-05 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suitor', '0008_suitor_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suitor',
            name='a',
        ),
    ]
