# Generated by Django 2.0.4 on 2018-05-06 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suitor', '0010_auto_20180505_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aprnc',
            name='id',
        ),
        migrations.RemoveField(
            model_name='suitor',
            name='aprnc',
        ),
        migrations.AddField(
            model_name='aprnc',
            name='suitor',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='suitor.Suitor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suitor',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suitor',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
